
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: johannes-nguyen-portfolio
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
