
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: johannes-nguyen-portfolio-prod
    ports:
      - "8080:80"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
