
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: johannes-nguyen-portfolio
    ports:
      - "8080:80"
    restart: unless-stopped
    # Add healthcheck
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
